### ISSUE TITLE
Licence confusion

### ISSUE THREAD

**Issue by steve-m-hay** [pmqs/DB_File#11]
The COPYRIGHT section of DB_File's main man page (https://metacpan.org/pod/DB_File#COPYRIGHT) refers to "the Berkeley DB FAQ (at http://www.oracle.com/technology/products/berkeley-db/db/index.html)," quoting some text from it which explains that it is not necessary to license Berkeley DB to use it in Perl scripts.

Unfortunately, that link now goes somewhere else (https://www.oracle.com/database/technologies/related/berkeleydb.html), which isn't an FAQ page. There is a "Berkeley DB FAQ" link on that page, which goes to https://www.oracle.com/database/technologies/berkeleydb-db-faq.html, but there is no sign of the text quoted in DB_File's man page...

That very much leaves one wondering what the licence situation now is, since Berkeley DB's own licences (a choice of two are available) do not sound as friendly as the text quoted in DB_File's man page would suggest.

Please could you clarify what the current situation is, and update the man page link and/or text appropriately.

**Comment by pmqs** [comment]
Hey Steve

Thanks for pointing that out. I wasn’t aware that change had been made.  Let me  see if I can get someone at Oracle to clarify the situation.

thanks
Paul

**Comment by steve-m-hay** [comment]
Hi Paul,
Is there any update on this?
Thanks,
Steve

**Comment by pmqs** [comment]
Hey Steve,

Yes. I've reached out to Oracle for clarification.  They don't think there will be a problem with getting the FAQ entry reinstated, but it needs to be checked by their legal department first. Hopefully that won't take too long.

Paul

**Comment by pmqs** [comment]
Hey Steve,

got some feedback from my contact at Oracle. They have checked with their legal department and the ruling is they will not reinstate the FAQ entry. Such is life.

That leaves `DB_File` in the the position where it is up to the end user to determine what the implications are with the combination of the Perl licence + the Oracle AGPL license. 

As far as my documentation is concerned, I can only highlight the existence of the licenses  and suggest that users make that call themselves.

thanks
Paul

**Comment by steve-m-hay** [comment]
Ok, Paul. Thanks for trying.

**Comment by pmqs** [comment]
DB_ 1.858 has updated license wording in POD 5089ede9dbc01ea9e47f5cb96bf9c8706ad1794d
