### ISSUE TITLE
Can a LICENSE file be added?

### ISSUE THREAD

**Issue by rpetit3** [pmqs/DB_File#8]
Hello! 

I'm submitting a recipe for DB_File to conda-forge. I was wondering if you could include a LICENSE file in your repo.

Or, would you rather I manually include a license for Perl_5 (https://dev.perl.org/licenses/) (e.g. text for Artistic License or GPLv1+, or both)

Thank you!

**Comment by pmqs** [comment]
I currently have a few references to a license for DB_File peppered in a few files. Does conda-forge abort if it doesn't explicitly find a file called LICENSE?

**Comment by pmqs** [comment]
Looking at https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=license it suggests that the LICENSE can be included with the recipe. Is that what you mean by "_manually including the license_"? I have no problems with you doing that.

**Comment by rpetit3** [comment]
Yeah that's exactly what I meant about manually including it.

I'll go ahead and do that. Thank you!
